services:
  rtmp-server:
    image: tiangolo/nginx-rtmp
    hostname: rtmp-server
    ports:
      - 1935:1935
  streamer:
    image: ffmpeg-streamer
    hostname: streamer
    volumes:
      - ./streamer:/streamer
    command: /streamer/run_stream.sh
    